### ISSUE TITLE
How to deal with "The request was aborted: Could not create SSL/TLS secure channel" error?

### ISSUE THREAD

**Issue by thecoderok** [splunk/splunk-sdk-csharp-pcl#59]
I am trying to run search example

```
static void Main(string[] args)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;
            using (var service = new Service(new Uri("https://splunk.tsi.lan")))
            {
                Run(service).Wait();
            }


            Console.Write("Press return to exit: ");
            Console.ReadLine();
        }

        static async Task Run(Service service)
        {
            await service.LogOnAsync(<user>, <password>); // error happen here

```

But I keep getting exception:

`The request was aborted: Could not create SSL/TLS secure channel`

How do I deal with it? Since sdk targets portable library, I can't use this workaround:

```
var handler = new WebRequestHandler();
handler.ServerCertificateValidationCallback = delegate { return true; };
```

Full stack trace:

```
System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at Splunk.Client.Examples.Program.Main(String[] args) in D:\Work\splunk-sdk-csharp-pcl-master\examples\normal-search\Program.cs:line 36
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=An error occurred while sending the request.
       Source=mscorlib
       StackTrace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Splunk.Client.Context.<SendAsync>d__37.MoveNext() in D:\Work\splunk-sdk-csharp-pcl-master\src\Splunk.Client\Splunk\Client\Context.cs:line 538
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Splunk.Client.Context.<GetResponseAsync>d__36.MoveNext() in D:\Work\splunk-sdk-csharp-pcl-master\src\Splunk.Client\Splunk\Client\Context.cs:line 504
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Splunk.Client.Context.<PostAsync>d__27.MoveNext() in D:\Work\splunk-sdk-csharp-pcl-master\src\Splunk.Client\Splunk\Client\Context.cs:line 382
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Splunk.Client.Context.<PostAsync>d__26.MoveNext() in D:\Work\splunk-sdk-csharp-pcl-master\src\Splunk.Client\Splunk\Client\Context.cs:line 357
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Splunk.Client.Service.<LogOnAsync>d__35.MoveNext() in D:\Work\splunk-sdk-csharp-pcl-master\src\Splunk.Client\Splunk\Client\Service.cs:line 283
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at Splunk.Client.Examples.Program.<Run>d__1.MoveNext() in D:\Work\splunk-sdk-csharp-pcl-master\examples\normal-search\Program.cs:line 46
       InnerException: 
            HResult=-2146233079
            Message=The request was aborted: Could not create SSL/TLS secure channel.
            Source=System
            StackTrace:
                 at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
                 at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
            InnerException: 

```

**Comment by shakeelmohamed** [comment]
Hi @thecoderok,

Can you try using one of the TLS versions on `SecurityProtocolType`? Splunk disables SSLv3 by default

**Comment by MACKAT05** [comment]
I had a similar error using
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;
on the recent 6.6 upgrade.

using 
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Seems to have resolved my issue
