### ISSUE TITLE
InvalidDataException while retrieving a list of saved searches for the specific app

### ISSUE THREAD

**Issue by r8zr** [splunk/splunk-sdk-csharp-pcl#70]
I'm experiencing a problem using SDK v2.2.5 while retrieving a list of saved searches for the specific app. I've gone through your code and seems like this is happening [right here](https://github.com/splunk/splunk-sdk-csharp-pcl/blob/master/src/Splunk.Client/Splunk/Client/AtomEntry.cs#L415).  A problematic name is different for different apps (for example: "action.customsearchbuilder.enabled", "action.slack.param.channel").

It is hard to say something about server version right now, but it should be quite old. But seems like on SDK v1.x everything was fine.

I'm not sure that this is your problem, but could you give any advice or workaround for such case?

Stack trace is always the same: 
`   at Splunk.Client.AtomEntry.<ParseDictionaryAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Splunk.Client.AtomEntry.<ParsePropertyValueAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Splunk.Client.AtomEntry.<ReadXmlAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Splunk.Client.AtomFeed.<ReadXmlAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Splunk.Client.BaseEntity`1.<ReconstructSnapshotAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Splunk.Client.EntityCollection`2.<GetAllAsync>d__12.MoveNext()`

**Comment by maxcra** [comment]
I am also experiencing this exact bug. I have asked for a solution on answers.Splunk.
https://answers.splunk.com/answers/543752/why-does-savedsearchesgetornullasync-throw-excepti.html

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
