### ISSUE TITLE
Unit tests fail - localisation issues

### ISSUE THREAD

**Issue by JohnPenney** [splunk/splunk-sdk-csharp-pcl#71]
I've just downloaded & built the Splunk C# SDK - on running unit tests I get 4 failures.  All seem to be related to my locale - I'm in the United Kingdom.  
```

---  Splunk.Client.UnitTests.TestAtomFeed.CanReadAtomEntry
Exception
Xunit.Sdk.EqualException: Assert.Equal() Failure
Position: First difference is at position 196
Expected: AtomEntry(Title=search search index=_internal | head 1000, Author=admin, Id=https://localhost:8089/services/search/jobs/scheduler__admin__search__RMD50aa4c13eb03d1730_at_1401390000_866, Published=5/29/2014 12:00:01 PM, Updated=5/29/2014 1:01:08 PM)
Actual:   AtomEntry(Title=search search index=_internal | head 1000, Author=admin, Id=https://localhost:8089/services/search/jobs/scheduler__admin__search__RMD50aa4c13eb03d1730_at_1401390000_866, Published=29/05/2014 20:00:01, Updated=29/05/2014 21:01:08)
   at Splunk.Client.UnitTests.TestAtomFeed.<CanReadAtomEntry>d__1.MoveNext() in C:\DevWork\Experiments\Splink\splunk-sdk-csharp-pcl-2.2.5\test\unit-tests\TestAtomFeed.cs:line 38

--- Splunk.Client.UnitTests.TestAtomFeed.CanReadAtomFeed
Exception
Xunit.Sdk.EqualException: Assert.Equal() Failure
Position: First difference is at position 92
Expected: AtomFeed(Title=jobs, Author=Splunk, Id=https://localhost:8089/services/search/jobs, Updated=5/29/2014 12:13:01 PM)
Actual:   AtomFeed(Title=jobs, Author=Splunk, Id=https://localhost:8089/services/search/jobs, Updated=29/05/2014 20:13:01)
   at Splunk.Client.UnitTests.TestAtomFeed.<CanReadAtomFeed>d__2.MoveNext() in C:\DevWork\Experiments\Splink\splunk-sdk-csharp-pcl-2.2.5\test\unit-tests\TestAtomFeed.cs:line 48

--- Splunk.Client.UnitTests.TestServerMessageCollection.CanConstructServerMessage
Exception
Xunit.Sdk.EqualException: Assert.Equal() Failure
Position: First difference is at position 11
Expected: 2014-05-27 15:28:02Z
Actual:   2014-05-27 23:28:02Z
   at Splunk.Client.UnitTests.TestServerMessageCollection.<CanConstructServerMessage>d__0.MoveNext() in C:\DevWork\Experiments\Splink\splunk-sdk-csharp-pcl-2.2.5\test\unit-tests\TestServerMessageCollection.cs:line 50


--- Splunk.ModularInputs.UnitTests.TestModularInputs.EventWriterReportsOnWrite 
Exception
Xunit.Sdk.TrueException: Assert.True() Failure
   at Splunk.ModularInputs.UnitTests.TestModularInputs.<EventWriterReportsOnWrite>d__17.MoveNext() in C:\DevWork\Experiments\Splink\splunk-sdk-csharp-pcl-2.2.5\test\unit-tests\TestModularInputs.cs:line 568


```

**Comment by ncanumalla-splunk** [comment]
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.
